import request from './request.js';

export const adminApi = {
  statistics: () => request.get('/admin/statistics'),
  users: (params) => request.get('/admin/users', { params }),
  createUser: (data) => request.post('/admin/users', data),
  updateUser: (id, data) => request.put(`/admin/users/${id}`, data),
  deleteUser: (id) => request.delete(`/admin/users/${id}`),
  userStatus: (id, data) => request.put(`/admin/users/${id}/status`, data),
  userRole: (id, data) => request.put(`/admin/users/${id}/role`, data),
  resetPassword: (id, data) => request.put(`/admin/users/${id}/password`, data),
  photos: (params) => request.get('/admin/photos', { params }),
  updatePhoto: (id, data) => request.put(`/admin/photos/${id}`, data),
  deletePhoto: (id) => request.delete(`/admin/photos/${id}`),
  batchPhotos: (data) => request.put('/admin/photos/batch', data),
  markExternalPhotoFailed: (id, data) => request.post(`/admin/photos/${id}/external-failed`, data),
  cacheExternalPhoto: (id) => request.post(`/admin/photos/${id}/cache-external`),
  batchCacheExternalPhotos: (data) => request.post('/admin/photos/external/cache', data),
  featurePhoto: (id, data) => request.put(`/admin/photos/${id}/feature`, data),
  visibilityPhoto: (id, data) => request.put(`/admin/photos/${id}/visibility`, data),
  albums: () => request.get('/admin/albums'),
  createAlbum: (data) => request.post('/admin/albums', data),
  updateAlbum: (id, data) => request.put(`/admin/albums/${id}`, data),
  deleteAlbum: (id) => request.delete(`/admin/albums/${id}`),
  tags: () => request.get('/admin/tags'),
  createTag: (data) => request.post('/admin/tags', data),
  updateTag: (id, data) => request.put(`/admin/tags/${id}`, data),
  deleteTag: (id) => request.delete(`/admin/tags/${id}`),
  mergeTags: (data) => request.post('/admin/tags/merge', data),
  comments: () => request.get('/admin/comments'),
  updateCommentStatus: (id, data) => request.put(`/admin/comments/${id}/status`, data),
  deleteComment: (id) => request.delete(`/admin/comments/${id}`),
  settings: () => request.get('/admin/settings'),
  updateSettings: (data) => request.put('/admin/settings', data)
};
